@startuml deployment
  title General Deployment

  node "Client Device" as Client_Device #616161 {
    node "Browser Environment" as Browser_Environment #757575 {
      node "Client App" as Client_App [[./client.svg]] #bdbdbd
    }
  }

  node "Server Device" as Server_Device #616161 {
    node "__Singleton Container__\n Minimum: 4vCPUs/16GB\n Recommended: 16vCPUs/32GB" as Singleton_Container #757575 {
      node "Application Server" as Application_Server [[./application.svg]] #9e9e9e

      frame "Querying" as Querying #9e9e9e {
        queue "__Apache Pulsar__\n Memory minimum: 2GB\n Memory recommended: 8GB" as Apache_Pulsar #bdbdbd
        Apache_Pulsar -ri0)- Application_Server

        node "__Apache Trino__\n Memory minimum: 4GB\n Memory recommended: 16GB" as Apache_Trino #bdbdbd
        Apache_Pulsar -[hidden]- Apache_Trino
        Application_Server -(0- Apache_Trino
      }

      frame "Caching" as Caching #9e9e9e {
        node "__Apache Airflow__\n Memory minimum: 4GB" as Apache_Airflow #bdbdbd
        Application_Server -0)- Apache_Airflow

        database "__ClickHouse__\n Memory minimum: 2GB\n Memory recommended: 4GB" as ClickHouse #bdbdbd
        ClickHouse -0)- Apache_Airflow
        Application_Server -ri(0- ClickHouse
      }

      database "File System" as File_System [[./fs.svg]] #9e9e9e
      Apache_Pulsar -(0- File_System
      Apache_Trino -ri(0- File_System
      Application_Server -(0- File_System
      ClickHouse -(0- File_System
      Apache_Airflow -le(0- File_System
    }
  }

  interface "/api/v1/hdio" as Public_REST_API
  Client_App --( Public_REST_API
  Public_REST_API -- Application_Server

  interface "/api/v1/sessions" as Sessions_REST_API
  Client_App --( Sessions_REST_API
  Sessions_REST_API -- Application_Server

  interface "/api/v1/tenants" as Tenants_REST_API
  Tenants_REST_API -- Application_Server
@enduml

@startuml client
  title Client App

  interface "/api/v1/hdio" as Public_REST_API
  interface "/api/v1/sessions" as Sessions_REST_API

  node "Client App" as Client_App #616161 {
    node "Worker Thread" as Worker_Thread #757575 {
      component "HDMLAggregator" as HDMLAggregator #bdbdbd

      component "HDMLParser" as HDMLParser #bdbdbd
      
      component "HDMLClient" as HDMLClient #bdbdbd
      Public_REST_API )--- HDMLClient
      Sessions_REST_API )--- HDMLClient

      component "HDMLBroker" as HDMLBroker #bdbdbd
      HDMLClient -le0)- HDMLBroker
      HDMLAggregator -0)- HDMLBroker
      HDMLParser -ri0)- HDMLBroker
    }

    node "Main Thread" as Main_Thread #757575 {
      component "<hdml-io>" as hdml_io #bdbdbd
    }
    Worker_Thread <-- hdml_io: initialize/terminate
    HDMLBroker -(0)- hdml_io
  }
@enduml


@startuml application
  title Application Server

  node "Application Server" as Application_Server #616161 {
    node "HyperData Service" as HyperData_Service [[./hyperdata.svg]] #9e9e9e
    node "Sessions Service" as Sessions_Service [[./sessions.svg]] #9e9e9e
    node "Tenants Service" as Tenants_Service [[./tenants.svg]] #9e9e9e
  }
@enduml


@startuml sessions
  title Sessions Service Deployment

  note as API
    **Endpoints:**
    ----
    * [[./ GET /api/v1/sessions/:tenant/request?ttl=:ttl&scope=:scope]]
    * [[./ GET /api/v1/sessions/:tenant?token=:token]]
  end note

  interface "/api/v1/sessions" as Sessions_REST_API
  API -- Sessions_REST_API

  node "Application Server" as Application_Server #616161 {
    node "Sessions Service" as Sessions_Service #757575
    Sessions_REST_API -- Sessions_Service
  }
  
  database "File System" as File_System [[./fs.svg]] #757575
  Sessions_Service -(0- File_System
@enduml


@startuml tenants
  title Tenants Service Deployment

  note as API
    **Endpoints:**
    ----
    * [[./ POST /api/v1/tenants]]
    * [[./ GET /api/v1/tenants/:tenant]]
    * [[./ PATCH /api/v1/tenants/:tenant]]
    * [[./ DELETE /api/v1/tenants/:tenant]]
  end note

  interface "/api/v1/tenants" as Tenants_REST_API
  API -- Tenants_REST_API

  node "Application Server" as Application_Server #616161 {
    node "Tenants Service" as Tenants_Service #757575
    Tenants_REST_API -- Tenants_Service

    ' ssh-keygen -t rsa -P "" -b 4096 -m PEM -f tenant.key
    ' ssh-keygen -e -m PEM -f tenant.key > tenant.pub
    ' ssh-keygen -t ed25519 -C "user@example.com" -f tenant.git -N ""
    node "ssh-keygen" as ssh_keygen #9e9e9e
    Tenants_Service -(0- ssh_keygen

    ' ssh-agent bash -c 'ssh-add ./data/tenant.git; git clone git@github.com:user/repos.git'
    node "ssh-agent" as ssh_agent #9e9e9e
    Tenants_Service -(0- ssh_agent

    ' git config core.sshCommand "$(which ssh) -i ./data/tenant.git"
    ' git config user.name "user"
    ' git config user.email "user@example.com"
    node "git" as git #9e9e9e
    Tenants_Service -(0- git

    ' javy compile -d -o ./bin/wasm/auth.wasm ./git/hooks/auth.js
    ' javy compile -d -o ./bin/wasm/patch.wasm ./git/hooks/patch.js
    ' javy compile -d -o ./bin/wasm/cache.wasm ./git/hooks/cache.js
    node "javi" as javi #9e9e9e
    Tenants_Service -(0- javi
  }

  queue "Apache Pulsar" as Apache_Pulsar #616161 {
    frame "tenants_req" as tenants_req_queue #9e9e9e
    frame "tenants_res" as tenants_res_queue #9e9e9e
  }
  Tenants_Service -ri(0- Apache_Pulsar

  database "File System" as File_System [[./fs.svg]] #757575
  Tenants_Service -(0- File_System
  ssh_keygen -(0- File_System
  ssh_agent -(0- File_System
  git -(0- File_System
  javi -(0- File_System
@enduml


@startuml hyperdata
  title HyperData Service Deployment

  note as API
    **Endpoints:**
    ----
    * [[../hyperdata/post_docs.svg POST /api/v1/hdio/:tenant/docs]]
    * [[./ GET /api/v1/hdio/:tenant/docs/:doc/htm]]
    * [[./ GET /api/v1/hdio/:tenant/docs/:doc/bin]]
    * [[./ GET /api/v1/hdio/:tenant/docs/:doc/obj]]
    * [[./ GET /api/v1/hdio/:tenant/docs/:doc/sql?frame=:frame&field=:name&field=:name]]
    * [[./ GET /api/v1/hdio/:tenant/docs/:doc/data?model=:model&field=:name&field=:name]]
  end note

  interface "/api/v1/hdio" as HDIO_REST_API
  API -- HDIO_REST_API

  node "Application Server" as Application_Server #616161 {
    node "HyperData Service" as HyperData_Service #757575
    HDIO_REST_API -- HyperData_Service
  }
  
  database "File System" as File_System [[./fs.svg]] #757575
  HyperData_Service -(0- File_System
@enduml


@startuml fs
  title File system

  folder "/hdfs" as hdfs #616161 {

    folder "sys" as sys #757575 {
      folder "keys" as sys_keys #9e9e9e {
        file "sys.key" as sys_key #bdbdbd
        file "sys.pub" as sys_pub #bdbdbd
      }

      folder "logs" as sys_logs #9e9e9e {
        file "pulsar.log" as pulsar_log #bdbdbd
        file "trino.log" as trino_log #bdbdbd
        file "clickhouse.log" as clickhouse_log #bdbdbd
        file "airflow.log" as airflow.log #bdbdbd
      }
      sys_keys -[hidden]-- sys_logs
      
      folder "data" as sys_data #9e9e9e {
        folder "pulsar" as pulsar_data #bdbdbd
        folder "trino" as trino_data #bdbdbd
        folder "clickhouse" as clickhouse_data #bdbdbd
        folder "airflow" as airflow_data #bdbdbd
      }
      sys_logs -[hidden]-- sys_data
    }

    folder "usr" as usr #757575 {
      folder ":tenant" as name #9e9e9e {
        folder "data" as usr_data #bdbdbd {
          file "tenant.key" as key #e0e0e0
          file "tenant.pub" as pub #e0e0e0
          file "tenant.git" as git #e0e0e0
          file "tenant.env" as dotenv #e0e0e0
        }

        folder "lib" as usr_lib #bdbdbd {
          folder "hooks" as hooks #e0e0e0 {
            file "auth.js" as auth_js #fafafa
            file "patch.js" as patch_js #fafafa
            file "cache.js" as cache_js #fafafa
          }
          folder "hdmls" as hdmls #e0e0e0 {
            file "model.html" as model_html #fafafa
            file "frame.html" as frame_html #fafafa
          }
        }
        usr_data -[hidden]-- usr_lib

        folder "bin" as usr_bin #bdbdbd {
          folder "wasm" as wasm #e0e0e0 {
            file "auth.wasm" as auth_wasm #fafafa
            file "patch.wasm" as patch_wasm #fafafa
            file "cache.wasm" as cache_wasm #fafafa
          }
          folder "docs" as docs #e0e0e0 {
            file "model.hash.m" as model_doc #fafafa
            file "frame.hash.f" as frame_doc #fafafa
          }
        }
        usr_lib -[hidden]-- usr_bin
      }
    }
  }  
@enduml