@startuml package
  title @hdml/renderer package

  package "@hdml/common" as common {
    class LitElement [[https://lit.dev/docs/api/LitElement/]] {
      +[[./LitElement_constructor.svg constructor()]]: LitElement
      ..
      +connectedCallback(): void
      +disconnectedCallback(): void
      ..
      +[[./LitElement_requestUpdate.svg requestUpdate()]]: void
      #[[./LitElement_performUpdate.svg performUpdate()]]: void
      #shouldUpdate(props: Map<string, unknown>): boolean
      #willUpdate(values: PropertyValues): void
      #[[./LitElement_update.svg update(values: PropertyValues)]]: void
      ..
      #firstUpdated(props: Map<PropertyKey, unknown>): void
      #updated(props: Map<string, unknown>): void
      #[[./LitElement_getUpdateComplete.svg getUpdateComplete()]]: Promise<void>
    }

    class UnifiedElement extends LitElement {
      +get uid(): string
    }
  }

  package "@hdml/renderer" as renderer {
    enum TickStyles {
      +"text"
      +"rect"
      +"ellipse"
    }

    enum CurveTypes {
      +"natural"
      +"linear"
      +"cubic"
      +"step"
      +"bezier"
      +"basis"
      +"cardinal"
      +"catmull-rom"
    }

    enum CurveBezierTangents {
      +"horizontal"
      +"vertical"
    }

    enum CurveCubicMonotonicity {
      +"x"
      +"y"
    }

    enum CurveStepChanges {
      +"before"
      +"middle"
      +"after"
    }

    interface TrackedStyle {
      ..size..
      +width: number
      +height: number
      ..position..
      +top: number
      +left: number
      ..paddings..
      +paddingTop: number
      +paddingRight: number
      +paddingBottom: number
      +paddingLeft: number
      ..cursor..
      +cursor: string
      ..line width..
      +lineWidth: number
      +lineWidthActive: number
      +lineWidthFocus: number
      +lineWidthHover: number
      ..line color..
      +lineColor: string
      +lineColorActive: string
      +lineColorFocus: string
      +lineColorHover: string
      ..line style..
      +lineStyle: string
      +lineStyleActive: string
      +lineStyleFocus: string
      +lineStyleHover: string
      ..fill color (background)..
      +fillColor: string
      +fillColorActive: string
      +fillColorFocus: string
      +fillColorHover: string
      ..font family..
      +fontFamily: string
      +fontFamilyActive: string
      +fontFamilyFocus: string
      +fontFamilyHover: string
      ..font size..
      +fontSize: string
      +fontSizeActive: string
      +fontSizeFocus: string
      +fontSizeHover: string
      ..font weight..
      +fontWeight: string
      +fontWeightActive: string
      +fontWeightFocus: string
      +fontWeightHover: string
      ..font style..
      +fontStyle: string
      +fontStyleActive: string
      +fontStyleFocus: string
      +fontStyleHover: string
      ..tick style..
      +tickStyle: TickStyles
      +tickWidth: number
      +tickHeight: number
      ..curve style..
      +curveType: CurveTypes
      +curveBasisBeta: number [0..1]
      +curveBezierTangents: CurveBezierTangents
      +curveCardinalTension: number [0..1]
      +curveCatmullRomAlpha: number [0..1]
      +curveCubicMonotonicity: CurveCubicMonotonicity
      +curveStepChange: CurveStepChanges
    }
    TrackedStyle -- TickStyles
    TrackedStyle -- CurveTypes
    TrackedStyle -- CurveBezierTangents
    TrackedStyle -- CurveCubicMonotonicity
    TrackedStyle -- CurveStepChanges

    abstract class AbstractChartElement {
      -_view: null | HdmlViewElement
      -_ssheet: CompletedCSSStyleSheet
      -_styles: CSSStyleDeclaration
      -_cache: null | TrackedStyles
      -_stored: TrackedStyles
      ..
      #{abstract} geometrySelector: null | string
      ..
      +get view(): null | HdmlViewElement
      +get styles(): CSSStyleDeclaration
      +get tracked(): TrackedStyles
      +get stored(): TrackedStyles
      ..
      +constructor(): AbstractChartElement
      ..
      +connectedCallback(): void
      +disconnectedCallback(): void
      +shouldUpdate(props: Map<string, unknown>): boolean
      ..
      #firstUpdated(props: Map<PropertyKey, unknown>): void
      #updated(props: Map<string, unknown>): void
      #resetStylesheets(sheets: CSSStyleSheet[]): void
      #updateStyles(): void
      ..
      #{abstract} renderGeometry(): void
      #{abstract} updateGeometry(): void
      ..
      -stylesChangedListener(): void
      -getStaticStyles(): lit.CSSResult
    }
    UnifiedElement <|-- AbstractChartElement
    AbstractChartElement *-- TrackedStyle

    abstract class AbstractStyleMapperElement {
      -_shadowStyle: CompletedCSSStyleSheet
      -_geometryStyle: CompletedCSSStyleSheet
      -_computedStyle: CSSStyleDeclaration
      -_trackedStyleStore: TrackedStyle
      -_trackedStyleCache: TrackedStyle
      ..
      #{abstract} selector: null | string
      ..
      +get geometryStyle(): CompletedCSSStyleSheet
      +get trackedStyle(): TrackedStyle
      ..
      #[[./AbstractStyleMapperElement_shouldUpdate.svg shouldUpdate]](props: Map<string, unknown>): boolean
      ..
      #clearTrackedStyleCache(): void
      #[[AbstractStyleMapperElement_updateStyles.svg updateStyles]](): void
      ..
      -[[AbstractStyleMapperElement_updateShadowStyle.svg updateShadowStyle]](): void
      #getShadowStyle(): string[]
      ..
      -[[./AbstractStyleMapperElement_updateGeometryStyle.svg updateGeometryStyle]](): void
      #[[./AbstractStyleMapperElement_getGeometryStyle.svg getGeometryStyle]](): string[]
      ..
      -getSvgStateStyle(state?: hover|focus|active): string
      -getSvgCursorStyle(state?: hover|focus|active): string
      -getSvgOutlineStyle(state?: hover|focus|active): string
      -getSvgFontFamilyStyle(state?: hover|focus|active): string
      -getSvgFontSizeStyle(state?: hover|focus|active): string
      -getSvgFontWeightStyle(state?: hover|focus|active): string
      -getSvgFontStyleStyle(state?: hover|focus|active): string
      -getSvgStrokeStyle(state?: hover|focus|active): string
      -getSvgStrokeWidthStyle(state?: hover|focus|active): string
      -getSvgStrokeDasharrayStyle(state?: hover|focus|active): string
      -getSvgStrokeLinecapStyle(state?: hover|focus|active): string
      -getSvgFillStyle(state?: hover|focus|active): string
    }
    UnifiedElement <|-- AbstractStyleMapperElement
  }
@enduml

@startuml LitElement_constructor
  title LitElement#constructor()

  start
    :[[./LitElement_requestUpdate.svg this.requestUpdate()]] ]
  end
@enduml

@startuml LitElement_requestUpdate
  title LitElement#requestUpdate()

  start
    :Adding request to the queue,\nasync dequeue.|
    :[[./LitElement_performUpdate.svg this.performUpdate()]] ]
  end
@enduml

@startuml LitElement_performUpdate
  title LitElement#performUpdate()

  start

    group Update
      if (this.shouldUpdate()) then (yes)
        :this.willUpdate()]
        :[[./LitElement_update.svg this.update()]] ]
      endif
    end group

    group PostUpdate
      if (!this.hasUpdated) then (yes)
        :this.firstUpdated()]
      endif
      :this.updated()]
      :[[./LitElement_getUpdateComplete.svg this.getUpdateComplete()]] ]
    end group

  end
@enduml

@startuml LitElement_update
  title LitElement#update()

  start
    :Reflects property values to attributes.]
    :this.render()]
  end
@enduml

@startuml LitElement_getUpdateComplete
  title LitElement#getUpdateComplete()

  start
    :resolve(this.updateComplete)]
  end
@enduml

@startuml AbstractStyleMapperElement_shouldUpdate
  title AbstractStyleMapperElement#shouldUpdate()

  start
    :this._trackedStyleCache !== this._trackedStyleStore/
  end
@enduml

@startuml AbstractStyleMapperElement_updateStyles
  title AbstractStyleMapperElement#updateStyles()

  start
    :this._trackedStyleStore = this._trackedStyleCache]
    :this.[[./AbstractStyleMapperElement_updateShadowStyle.svg updateShadowStyle]]()]
    :lit.adoptStyles(this.renderRoot, [this.staticStyle, ...this._shadowStyle])]
    :this.[[./AbstractStyleMapperElement_updateGeometryStyle.svg updateGeometryStyle]]()]
    :this.dispatchEvent("@hdml/renderer.ElementStyleUpdated")]
  end
@enduml

@startuml AbstractStyleMapperElement_updateShadowStyle
  title AbstractStyleMapperElement#updateShadowStyle()

  start
    :styles = this.getShadowStyle()]
    while (i = this._shadowStyle.cssRules.length - 1; i >= 0; i--)
      :this._shadowStyle.deleteRule(i)]
    endwhile
    while (styles.forEach(rule))
      :this._shadowStyle.insertRule(rule)]
    endwhile
  end
@enduml

@startuml AbstractStyleMapperElement_updateGeometryStyle
  title AbstractStyleMapperElement#updateGeometryStyle()

  start
    :styles = this.getSvgStyle()]
    while (i = this.geometryStyle.cssRules.length - 1; i >= 0; i--)
      :this.geometryStyle.deleteRule(i)]
    endwhile
    while (styles.forEach(rule))
      :this.geometryStyle.insertRule(rule)]
    endwhile
  end
@enduml

@startuml AbstractStyleMapperElement_getGeometryStyle
  title AbstractStyleMapperElement#getGeometryStyle()

  start
    :default = getSvgStateStyle()]
    :active = getSvgStateStyle("active")]
    :focus = getSvgStateStyle("focus")]
    :hover = getSvgStateStyle("hover")]
    :return [default, active, focus, hover] /
  end
@enduml